### ISSUE TITLE
Issues to be addressed at the WAVE meeting at NAB 2017

### ISSUE THREAD

**Issue by wilaw** [cta-wave/technical-working-group#2] opened 2017-02-15 15:59 UTC
WAVE will hold a one-day face-to-face joint workshop for all task forces on Thursday, 4/27, from 9am to 4pm.  Lunch will be provided during a 12pm-1pm lunch break.
 
The format of this workshop will be optimized to discuss **issues.** which are best debated face-to-face.  Issues can be of specific interest to a single TF, or of general interest.  We’ll organize breakouts as seem to be appropriate once we have the issues assembled. 

This tracker is the means by which these issues are submitted for discussion. To submit a new issue, reply with a new COMMENT on this issue. In the comment, please be sure to add the following information:
1. Your name as the topic submitter
2.  A brief title to describe the issue
3. A paragraph describing the issue to be addressed and debated. This will be shown on screen during the NAB workshop while the issue is addressed.

**Comment by johnsim** [comment] 2017-04-12 02:58
1. Title: Regionalization and the content specification
Description: What are the regionalized WAVE use cases and how might they impact the content specification? Our discussion about whether 50 vs. 60 Hz. framerate regionalization is necessary has resulted in the need to discuss regionalization use cases which can impact each of our specifications. Elements of this discussion thus far: the assertion that TVs can handle 50 and 60 Hz framerates, that many 50 Hz TVs might not have been adequately tested with 60 Hz content, a TV may handle 50 and 60 Hz framerates fine, but not the dynamic switching of framerates, and that this issue can be even more challenging over HDMI. From this we agreed that we must start by identifying the required use cases and document the requirements these use cases place on our specifications, in this case the content spec.

**Comment by johnsim** [comment] 2017-04-12 03:00
2. Title: Splice conditioning and the content specification
Description: Are their splice conditioning requirements that should be including in the content specification? Normative? Informative? Splice Conditioning: There is a need to support single decoder devices and therefore splice conditioning needs to be addressed in the content spec. It was noted that the problem is more complicated that splice conditioning. There will be content that is not conditioned. This needs to be addressed at the DPCTF – what to do when content splices are not conditioned.

**Comment by johnsim** [comment] 2017-04-12 03:00
3. Title: Presentation Profile Requirements
Description: What are the requirements for including a Presentation Profile in the content specification? (TBD – already agreed to include but without language on requirements. Here is the draft MSFT proposal from January - 1. Consists of already published WAVE Media Profiles, 2. Unlike media profile, Follows rather than leads industry – at least one service and one device commercially using this presentation profile, 3) Support from six WAVE member companies – OR, Perhaps require that presentation profiles must consist of media profiles which meet 3.2.2.1 market relevance?

**Comment by bobcampbell-resillion** [comment] 2017-04-19 15:55
Title: TCTF present overview of their agreed testing approach
Description: I can present the slides we have agreed [WAVE-Test-Approach-Outline.pptx](https://github.com/cta-wave/technical-working-group/files/935835/WAVE-Test-Approach-Outline.pptx). There's several specific discussion points that should lead from this that I will list below...

**Comment by bobcampbell-resillion** [comment] 2017-04-19 15:56
Title: Who should be able to access a WAVE test suite? 
Description: Only WAVE members, only customers of testing companies, general public ? Or are all available, but with different levels of usefulness?

**Comment by bobcampbell-resillion** [comment] 2017-04-19 15:58
Title: How will WAVE compliance testing be conducted?
Description: The TCTF is planning to ensure that its work allows for a WAVE compliance program. Its so far not been resolved whether that might be operated by WAVE itself, and how that testing will be conducted. Could involve aspects of self-test, 3rd party managed, commercial qualification program, even a logo program...

**Comment by bobcampbell-resillion** [comment] 2017-04-19 16:05
Title: What are the set of test areas in scope for WAVE testing?
Description: 
TCTF is proposing 3 levels of breakdown
1. test area – see suggested breakdown slide 8 of test approach deck.
2. test group – groups of related tests E.g. closed caption test playback, seamless switching playback, tests for JS object X, roughly corresponds to rows in the current Google doc.
3. test case – most atomic test case that tests a single clause in the spec. Test case maps 1-to-1 with test assertion.
Does the high level test area set match expectations?

**Comment by bobcampbell-resillion** [comment] 2017-04-19 16:11
Title: How will the work to define a high level test plan be allocated between TFs?
Description: A test plan gives you an idea of what full coverage would be, but does not incur the costs of development (yet). It will allow WAVE to identify which test case(s) are covered by member contributions and where there are gaps. To create this test plan there are a number of steps and it requires expertise from the "subject matter expert" TFs as well as the TCTF. See slide 9 of test approach deck. Does the allocation match expectations, and if so, do the TFs have capacity to do the work in a timeframe that meets the overall schedule?

**Comment by bobcampbell-resillion** [comment] 2017-04-19 16:15
Title: What are the requirements of the WAVE test environment?
Description: The TCTF has proposed a number of test tools (see test approach deck slides 12-17) and has agreed a number of use cases in https://standards.cta.tech/apps/org/workgroup/tctf/download.php/19752/tctf-00013-v003-WAVE%20Test%20Approach.docx) 

What are the high priority/key requirements for the test environment?

**Closed as completed** 2021-03-22 13:45 UTC
