### ISSUE TITLE
Topics for discussion at the IBC-adjacent WAVE Meeting Sept 14

### ISSUE THREAD

**Issue by ablasgen** [cta-wave/technical-working-group#26] opened 2023-07-31 13:53 UTC
WAVE is holding an IBC-adjacent meeting on Thursday, September 14 from 1-5 pm CEST.

Use this issue tracker to contribute discussion items. Please note that although no decisions can be made during this informal meeting, points raised during this discussion can be forwarded to WAVE TFs and/or the upcoming WAVE Workshop.

For each item, please suggest a title, and provide some background text as well as the decision to make or call-to-action.

**Comment by wilaw** [comment] 2023-08-14 16:19
Managed media source - implications for the industry? What effect will this have on the vision of HTML5 as a common media application platform?
See minutes here https://www.w3.org/2023/07/25-me-minutes.html , issue thread https://github.com/w3c/media-source/issues/320 and also video here https://developer.apple.com/videos/play/wwdc2023/10122/ for background.

**Comment by haudiobe** [comment] 2023-08-14 17:04
Potential New topics for next release of DPC spec

- Migration of Test Content to Content Specification
- Addressing backlog 
- Codecs and Media Profiles
  - HEVC with different profiles
  - Additional Audio Profiles
  - Dynamic Mapping
  - VVC and AV1
- Commercial DRM
- Test Description improvements
  - Better test description
  - Type 1 tests for players
  - Additional tests (splicing, events, etc.)
- Additional functionality testing
  - HTTP stack
  - Network performance
- Collecting feedback from users of the specification and test suite

**Comment by haudiobe** [comment] 2023-08-14 17:05
Reply LS to DASH on Test Content Availability

https://standards.cta.tech/apps/org/workgroup/wtwg/download.php/31896/latest/DASH-IF L202106 CTA-WAVE.pdf

**Comment by ablasgen** [comment] 2023-08-14 17:16
@haudiobe Hi Thomas, just a note to point out that we did reply to that LS: https://standards.cta.tech/apps/org/workgroup/wtwg/download.php/36859. 

Or maybe the point of your comment on the DASH-IF LS was different? If you could clarify the call to action, that would be helpful!

**Comment by haudiobe** [comment] 2023-08-14 20:29
> @haudiobe Hi Thomas, just a note to point out that we did reply to that LS: [standards.cta.tech/apps/org/workgroup/wtwg/download.php/36859](https://standards.cta.tech/apps/org/workgroup/wtwg/download.php/36859).
> 
> Or maybe the point of your comment on the DASH-IF LS was different? If you could clarify the call to action, that would be helpful!

We responded but the response is not complete and should be updated based on the recent work.

**Comment by haudiobe** [comment] 2023-08-21 10:48
I suggest that we add a discussion on climate impacts for streaming services to the discussion and if CTA WAVE could do anything useful in this regard. Examples include extending CMCD to collect power consumption/energy related metrics, and other aspects. @wilaw has a presentation on this matter. We may even as some of the colleagues from Greening of Streaming to give a presentation.

**Comment by jpiesing** [comment] 2023-09-06 09:20
There's some overlap with Thomas's item above but I would like to discuss candidates and priorities for the next revisions of the test suite - a discussion that will no doubt continue at Fall Forum with a different set of people.

- For the next release (Q1 2024?), here are the candidates in some sort of descending order of probability. These are principally items where work has started or are a small edit to what we already have.
-- The Resilion audio work that is completed and was not merged into the first release (Dolby audio codecs, audio observations)
-- Basic 'chh1' SDR HEVC where @rbouqueau has just uploaded some encoded streams
-- More HEVC SDR media profiles 
-- Improving usability 
-- Bug fixes
- For following releases, here is a list, this time in no particular order. These are items where work has not started.
-- HDR HEVC media profiles
-- AV1
-- VVC
-- More audio media profiles
-- Commercial DRM
-- Other items in the backlog
-- More bug fixes and usability improvements

**Comment by wilaw** [comment] 2023-09-11 10:41
At the W3C Media and Entertainment Interest Group meeting on Sep 11 in Seville, chaired by Chris Needham,  the group discussed the problem of media application development on TVs. @JohnRiv presented HTML5 vs native streaming survey and Web Media API Snapshot and Louay Bassbouss presented the WAVE DPCTF Testing and Web Media API Test suite (). Concern was that the problem is not being solved because the current fractured app dev space benefits (to some degree) the leading content distributors and hardware manufactures. While there is a long term gain for all constituents with a common app model, there is short term pain in implementing such features and hence we get little change.

The proposal is for CTA WAVE, as the nexus between TV manufacturers and content distributors, to 
1. Develop a performance based test suite for HTML5 media development on TVs (based on the Streaming Media Test Suite)
2. Develop a program to create and maintain definitions of acceptable performance thresholds under this test suite. 
3. Work with W3C to add new APIs that are needed (such as a standard way to launch web URLs and web apps)
4. Create a group of content distributors who commit to only offering their content if this performance threshold is met on a TV.
5. Grow this group until it presents the majority of brands distributing  TV content, at which point TV manufacturers can enforce that it is the only app environment they will support and they can cease supporting custom app environments.

**Comment by jpiesing** [comment] 2023-09-14 14:18
Browser rendering of subtitles and captions

The minutes of W3C TTML group meeting at TPAC (https://www.w3.org/2023/09/12-tt-minutes.html) include a discussion about promoting browser rendering of subtitles / captions and about CTA WAVE testing of subtitle / caption rendering.
We have not communicated that the reason why we do not test subtitle / caption rendering is because we expect this to be done by a JavaScript library and not by the browser. The W3C TTML group seem to think this is not a permanent or desirable situation.
- We could just communicate what we have decided.
- If imsc.js has dependencies on any features of the browser that are not normally tested then perhaps we could consider testing those? There is some discussion in the W3C meeting notes about using JavaScript libraries for rendering subtitles / captions using VTTCue. 
- We could consider more complete testing of subtitle / caption rendering assuming browser rendering. HbbTV and DVB-I include this.

**Closed as completed** 2024-09-25 20:54 UTC
